### ISSUE TITLE
Builtin for push()

### ISSUE THREAD

**Issue by jrha** [quattor/pan#108]
As mentioned in #53 and #103 it would be good to have a push-like function as a compiler built-in.

If the left hand side of the assignment is a list, it should `append` each of the passed arguments to that list.
i.e.

``` pan
'/foo' = list('spam');
'/foo' = push('beans', 'eggs');
```

Should result in:

``` json
"foo" : ["spam", "beans", "eggs"],
```

If the left hand side of the assignment is a dictionary, it should `merge` the passed arguments.
i.e.

``` pan
'/foo' = dict('spam', true);
'/foo' = push('beans', false, 'eggs', false);
```

Should result in:

``` json
"foo" : {
    "spam" : true,
    "beans" : false,
    "eggs" : false,
},
```

**Comment by ned21** [comment]
I am not keen on mixing push() for lists and dicts. Moving npush() to a compiler built-in would be nice I suppose but the separate names are helpful for understanding the type being manipulated.

**Comment by jrha** [comment]
`npush` or `dpush`?

**Comment by DChambersSTFC** [comment]
From what I can see, the Pan push() function works the same way as described here. Also, if the list being pushed to doesn't exist, an empty one will be created before being added to. If one of the arguments is a list itself, it will be appended as a list within the list being pushed to.

E.g
```
'/foo' = list('spam');
'/bar' = list('beans', 'eggs');
'/foo' = push(bar);
```
would result in

`"foo" : ["spam", ["beans", "eggs"]],`

For now, I will be trying to reproduce the behaviour of the Pan function into Java, without making any changes to behaviour.

**Comment by stdweird** [comment]
can we also clarify the behviour in dml blocks, so we are certain https://github.com/quattor/template-library-core/issues/104 is not "a feature"

**Comment by stdweird** [comment]
@DChambersSTFC i'm not sure that mixing types in a list is a feature we want.
to proceed, we should first agree on the unittests (ie the pancode and the produced json profile)

**Comment by jrha** [comment]
@stdweird as discussed at the workshop, I'm pretty sure that  quattor/template-library-core#104 isn't a feature, so it would be good to guard against it.

**Comment by DChambersSTFC** [comment]
Would it be appropriate to restrict all arguments to be the same type then?

**Comment by stdweird** [comment]
yes, i think so.
@DChambersSTFC are you going to add these to pan (as in 'add code')? (i'm asking because we have a summerstudent starting in 2 weeks to have a look at pan and howto possibly add new builtins and refine some error messages)

**Comment by DChambersSTFC** [comment]
I'm working on adding them currently as I'm also new to pan and using this issue to learn my way around.

**Comment by jrha** [comment]
I would be good for @DChambersSTFC and your student to collaborate then!

**Comment by DChambersSTFC** [comment]
My main obstacle currently is referencing the object that called the function. Is anyone familiar on the use of the SetSelf function or knows of what I should be using?

**Comment by stdweird** [comment]
@jrha @DChambersSTFC are you keeping notes how to add this (incl docs and unittests)? it's was basically the first thing we were going to ask our student: document how and were to add code and docs and tests for a new builtin. mayube they can meet during q4b?

**Comment by DChambersSTFC** [comment]
@loomis Do you know how I can reference the object calling the function?

**Comment by loomis** [comment]
@DChambersSTFC The "Context" object passed into the functions contains the full context of the compilation, including the current state of the object being built and the reference to "self".  See the "Context" interface for the full list of available methods.

Be very careful about mutating data structures that you access directly.  They are often shared between object templates and direct mutation can cause concurrency issues or serialization of incorrect values.

**Comment by ned21** [comment]
We decided at today's workshop in LAL that adding a built-in for push() would break all existing PAN code that uses the function from template-core. While cleaning up code might be possible, any change in behaviour between the current function and the built-in would lead to more subtle bugs so this is not worth the effort.

**Comment by jrha** [comment]
:disappointed:
