### ISSUE TITLE
final default variable

### ISSUE THREAD

**Issue by stdweird** [quattor/pan#109]
is this intended behaviour? if you can't modify a final default variable, maybe the compiler should throw an error or warning

```pan
object template t;

final variable X ?= 1;
variable X = 2;
```

```
[stdweird@gastn039a1 tmp]$ panc t.pan 
evaluation error [/tmp/t.pan:4.1-4.15]
cannot modify final global variable
>>> call stack trace 
>>> [/tmp/t.pan:4.1-4.15]
>>> ====================

```

**Comment by jouvin** [comment]
For me, this is expected. Whether the value is assigned as a default value  or not should not change the behaviour. After the `final` statement, the value should be protected against changes. What should work  (not tested!) is:
```
variable X = 2;
final variable X ?= 1;
```
but this probably doesn't address your use case...

**Comment by stdweird** [comment]
@jouvin what should be the resulting value in your example?

**Comment by jouvin** [comment]
2! At least this is my guess (and any attempt to modify `X` later should fail), I didn't try.

**Comment by ned21** [comment]
This looks expected to me too. ```final variable X ?= 1;``` means that no further modifications to X are allowed even if the value was previously set.

**Comment by stdweird** [comment]
ok, thinking a bit more about it, i now also agree and see possible use cases for. but not the code i was working with :smile:
