### ISSUE TITLE
require java 8

### ISSUE THREAD

**Issue by stdweird** [quattor/pan#120]
is there any reason to support anything except java 8 or later?

**Comment by jouvin** [comment]
I remember discussing this with @loomis a number of times and his position (he convinced me!) was to support the latest Java (and encourage people to use it) but to require (and thus build on) the oldest possible one that had all the required features (probably Java 5 or 6).

It's true that with all the security vulnerability in these old versions (in particular all the things related to SSL), it may be reasonnable to require Java 8...

**Comment by loomis** [comment]
Java 8 is the only one currently supported by Oracle.  Requiring it is probably reasonable.  You should check with MS; however, there were running old versions of java at some point in the past. Also at some point Java 8 OpenJDK wasn't easily available on all OSes (Ubuntu 14.04 is one, I believe). This may have changed.

**Comment by stdweird** [comment]
@ned21 @gombasg tougths/objections?

**Comment by ned21** [comment]
Java 8 is fine.

**Comment by stdweird** [comment]
@iliclaey can you have a look at this? i found http://maven.apache.org/enforcer/enforcer-rules/requireJavaVersion.html to set a minimal java version. i'll fix jenkins next week

**Comment by stdweird** [comment]
Fixed in https://github.com/quattor/pan/pull/118/commits/55c668c6fbef28074508573efd3952b603823856 and jenkins now tests with jdk1.8.0
