### ISSUE TITLE
Add function for value_if_exists

### ISSUE THREAD

**Issue by jrha** [quattor/pan#139]
A pattern we see a lot is:

```pan
variable FOO = if (path_exists('/system/thing/stuff')) {
    value('/system/thing/stuff');
};
```

It would be much neater if we could just do something like:

```pan
variable FOO = value_if_exists('/system/thing/stuff');
```

**Comment by stdweird** [comment]
imho, your example is missing the else block.

i propose to add default options value, so a default is set when no path exists, e.g.
```pan
variable FOO = value('/system/thing/stuff', undef);
```

**Comment by jrha** [comment]
I like your suggestion.

It is missing the else block, but that was intentional, you will often find the defaults further down implemented with...
```
variable FOO ?= 'default_value';
```

**Comment by stdweird** [comment]
hmmm, in that case, the default value won't help, probably make things worse.
coudl we make `SELF` the default default value? (ie in case there's only one argumnet to value, and that path doesn't exist, use `SELF`? (it would have the side effect that value might not fail anymore on any path; so faulty pan code might suddenly compile)

**Comment by jrha** [comment]
I don't like hidden behaviours, I think if you want `SELF` you should ask for it.

In terms of the `?=` defaults stuff...
```pan
variable FOO = value('/system/thing/stuff', undef);
```
Would work for us.

**Comment by ned21** [comment]
Are you really using global variables like that? Or is it just an overly simple example? Why not just replace the global with direct access to the path since my definition anywhere you could have used the global the path value is available?

**Comment by jrha** [comment]
Overly simple example... but not too unrealistic.
