### ISSUE TITLE
panlint: No spaces should be required inside []

### ISSUE THREAD

**Issue by ned21** [quattor/pan#143]
panlint is currently suggesting that this is the correct way to space an expression inside [] 
```
realm = pc_r[len - 1];
```

when other languages (e.g. python) prefer:

```
realm = pc_r[len-1];
```

cf. https://github.com/quattor/configuration-modules-core/pull/1048#discussion_r103177777

**Comment by stdweird** [comment]
The fix in #145 only supports simple expressions in square brackets
