### ISSUE TITLE
panlint requires 4 space indentation on continuation lines

### ISSUE THREAD

**Issue by jouvin** [quattor/pan#146]
As show the example in https://github.com/quattor/template-library-core/pull/154/commits/9e27de2870876f68fdb3514952f4d97166b5547f, panlint insists on having a 4 space indentation on continuation lines, like:
```pan
format('string_fmt %s',
            arg1);
```
this is inappropriate and if anything is enforced in this case, it should be left alignement between all argument lines, like:
```pan
format('string_fmt %s',
       arg1);
```

**Comment by jrha** [comment]
It is in fact by design, as I highly dislike continuations used in this way and much prefer the line to be rewritten as:

```pan
format(
    'string_fmt %s',
    arg1
);
```

**Comment by jrha** [comment]
So you would like to support:
```pan
format('string_fmt %s',
        arg1);
```

**Comment by jrha** [comment]
Panlint does not actually parse the language, so this cannot be supported easily.
I can allow the check to be disabled in a future version though.
