### ISSUE TITLE
Cannot release with Java 1.8

### ISSUE THREAD

**Issue by jrha** [quattor/pan#148]
Unfortunately codebase now requires Java 1.8.

Related to quattor/maven-tools#159

**Comment by jouvin** [comment]
Fortunately :-)

**Comment by jrha** [comment]
Fortunately it now works with 1.8, unfortunately it requires it?

**Comment by jouvin** [comment]
The opposite :-) Fortunately it requires 1.8 :-) 1.6 and 1.7 have severe security problems and it is good we cannot use them anymore... Personnally, I think, as said at the workshop, that we should require 1.8 for our Java tools in future releases (it means updating the `maven-compile-plugin` that still requires 1.5 as a minimum).
