### ISSUE TITLE
pan dict keys support relative panpath

### ISSUE THREAD

**Issue by stdweird** [quattor/pan#162]
this might open Pandora's box but i would like to avoid nested dict/list structures and use panpath syntax in dict keys, eg

```pan
"/a" = dict(
  "c/b/0", "value",
  ...
);
```
instead of 
```pan
"/a" = dict(
  "c", dict(
      "b", list("value"),
  ...
);
```

good idea or pure laziness?

**Comment by ned21** [comment]
Hard to tell from such an example which should already be optimised to:
```
"/a/c/b" = list("value");
```

Do you have a larger examples so we can evaluate it?

**Comment by jrha** [comment]
It scares me… but you must have had a reason for wanting it… right?

**Comment by jrha** [comment]
It would also require some way of resolving conflicts.

e.g. how should the following be dealt with?

```pan
"/a" = dict(
    "c/b/0", "value",
    "c", dict(
        "b", list("value2"),
    ),
);
```

**Comment by stdweird** [comment]
dunno, what does pan do with
```pan
"/a" = dict("a", 1, "b", 2", a" ,3);
```
probably the same

**Comment by jrha** [comment]
:man_shrugging:

**Comment by jrha** [comment]
Well in that specific example it throws a parse error :stuck_out_tongue: 
```
parse error [/tmp/test.pan:3.27-3.3]
Encountered: , a
```

Once the quotes are fixed, it throws a syntax error:
```
syntax error [/tmp/test.pan:3.8-3.35]
duplicate key (a) in nlist function
```

**Comment by stdweird** [comment]
the use case is metaconfig 😄 
using it garantees very long pan paths, so using absolute path on lefthandside of assignment is unusable and so are frequent prefixes.

example use case if for configuring services which require complicated schemas like https://github.com/quattor/configuration-modules-core/blob/master/ncm-metaconfig/src/main/metaconfig/logstash/5.0/tests/profiles/config.pan#L25

another use case are ordered dicts (new rsyslog metaconfig), so we are forced to use single element dict in list, which makes simple configuration look horrible if you have to writeout the structure.

another solution i tought of would be to improve prefix somehow, were we can set absolute prefix in the beginning and support relative prefix, always relative to absolute prefix
```
prefix "/a/b/c";
...
prefix "d/e";
...
prefix "e/f"
...
```
would be equal to current
```
prefix "/a/b/c";
...
prefix "/a/b/c/d/e";
...
prefix "/a/b/c/e/f"
...
```
but that sounds a bit complicated (but not necessarily very error prone; eg relative prefix without previous defined absolute should raise syntax error etc etc)

**Comment by stdweird** [comment]
the logstash example has another difficulty because we use append there, and are thus forced to break up the lefthand side and the values. if only we could also do 
```pan
"/a/b/+/d/e" = ...
```
instead of 
```pan
"/a/b" = append(dict('d', dict('e', ...));
```
switching to structue templates is not that nice either

**Comment by stdweird** [comment]
relative prefixes is pretty easy to add, see #165

**Comment by stdweird** [comment]
wrt logstash / append issue, i added #170, so now we can reference the last element of a list in a prefix as follows 
```pan
"/a/b" = append(undef);
prefix "/a/b/-1/c/d";
...
```
combined with #165, this should simplify things quite a lot

**Comment by ned21** [comment]
Superseded by #165
