### ISSUE TITLE
delete a variable

### ISSUE THREAD

**Issue by stdweird** [quattor/pan#176]
In the aftermath of #93 and PR #175, do we want a way to remove a variable?

ie
```pan
variable X = magic;
"/a" = exists(X);
```
to return `false`.

we can always do cisco-style
```pan
no variable X;
```
if we don't want any more magic values then we already have

**Comment by jrha** [comment]
I can't think of a situation where I would want to do this, so :-1: from me.

**Comment by ned21** [comment]
The least confusing syntax to use is to assign null and we already decided in #93 that it was too complex to make that the case. Introducing new syntax is unnecessary overhead, the use of `undef` is a suitable workaround in every scenario I can think of.

**Comment by jrha** [comment]
Agreed at April 2018 workshop, the answer is no.
