### ISSUE TITLE
final and schema default

### ISSUE THREAD

**Issue by stdweird** [quattor/pan#189]
Consider the following example template
```
object template t;
type x = string = 'abc';
bind "/a" = x;                                                                                                                                           
final "/a" = undef;
```
currently this compiles successfully and produces `"/a" = "abc"` result.
however, this looks like something gets modified after final due to the schema default.

i would like to doublecheck that this is intended behaviour for `final` and schema defaults (before i start relying on it :smile: ).

similar example without `undef`:
```pan
object template t;
type x = {
    'z' ? long
    'y' : string = 'abc'
};
bind "/a" = x;
final "/a" = dict();
```
results in `"/a/y" = "abc"` result

**Comment by jrha** [comment]
My understanding is that this is the correct/intended behaviour as defaults are applied after the templates have been interpreted and `final` only applies to the logic of the Pan code, not anything that happens to the profile after it has been run.

**Comment by ned21** [comment]
Agree this is correct. ```final "/a" = undef;``` looks odd but says: "/a must be the default value and cannot be any other"
