### ISSUE TITLE
option to compile included template late/last

### ISSUE THREAD

**Issue by wdpypere** [quattor/pan#208]
I'm trying to build a profile, and once the full profile is there use the values of ```/software/components/download``` to see which certificates are downloaded. This so I can build monitoring to validate said certificates.
However I can't seem to include my "post processing" template late enough in the process to be certain I get the full list.
Is there a way (or should there be a way) to make sure an included template is compiled last (or very late)?

**Comment by jouvin** [comment]
Not sure to fully understand the issue. The inclusion order is the order of appearance... If you want it to be the very last thing, you need to ensure that this is the very last thing done in your profile. In Aquilon, this is very easy: there is one template (`archetype/final`)  which is the very last one included. 

In SCDB, you have to put it in the node profile as the very last thing. If you followed the recommendation to have the following line as the last of your profile:

```
include PKG_REPOSITORY_CONFIG ;
```
Then it should be easy to plug your template by finding where this variable is defined (typically, in the cluster `site/cluster_info.pan`) and change the variable definition to be a site template that includes both your template and the one pointed by the variable before.

**Comment by stdweird** [comment]
@jouvin that might work, but it's not really what we want. e.g. only profiles that included a certain template should do this.
the functionality we are looking for is similar to `validate`, but with the possibiility to modify data in the tree.

**Comment by jrha** [comment]
Do as @jouvin suggests, but switch it with a variable that only gets set by the "certain template"?

**Comment by stdweird** [comment]
@jouvin @jrha for now, sure. but is there a reason why we shouldn't add this to pan?

**Comment by jrha** [comment]
Other that it seems like it could be horribly confusing?

**Comment by stdweird** [comment]
@jrha yes
(and wrt confusing; it's no worse than schema default value insertion or validate imho. debugging pan is horrible anyway)
