### ISSUE TITLE
panlint indentation style unexpected

### ISSUE THREAD

**Issue by jouvin** [quattor/pan#215]
`panlint` style for indentation of a multiple line statement is that every line after the first line must be indented by a multiple of 4 spaces, instead of using the approach found in all other languages where the continuation lines must be aligned with an opening parenthes, curly brace, bracket if there was one on the previous line. IMO this is unexpected and making the resulting code difficult to read when the goal of linting is to make it easier...

As an example, a code matching `panlint` requirements:

```
'/software/components/filecopy/services/{/etc/squid/customized.sh}' =
    dict('config', format(file_contents('features/frontier/customized.sh.file'),
                        FRONTIER_LOCAL_NET_STRING,
                        FRONTIER_HOST_MONITOR_STRING,
                        FRONTIER_CACHE_MEM,
                        FRONTIER_CACHE_DIR,
                        ),
        'restart', 'service frontier-squid reload',
        'perms', '0644');
```

when the expected code formatting, IMO, would have been:

```
'/software/components/filecopy/services/{/etc/squid/customized.sh}' =
    dict('config', format(file_contents('features/frontier/customized.sh.file'),
                          FRONTIER_LOCAL_NET_STRING,
                          FRONTIER_HOST_MONITOR_STRING,
                          FRONTIER_CACHE_MEM,
                          FRONTIER_CACHE_DIR,
                         ),
         'restart', 'service frontier-squid reload',
         'perms', '0644');
```

(I have no strong opinion whether we should impose or not the closing parenthesis to be on a separate line, it is not the case today. But if it is on a separate line, it is better if it is aligned with the opening one than the previous lines).

In addition to the discussable style adopted by `panlint`, it requires a time-consuming work to fix all the modified templates of the template library that where written with the "common style" in mind...

**Comment by jrha** [comment]
@jouvin the panlint "requirement" was never meant to deal with code written this way and now I finally understand why you are complaining! Your first example of the "required" formatting is clearly horrible and I never intended to force anyone into formatting code into this kind of mess.

Our "house style" at RAL would to be to write your example as follows, which should hopefully explain why I have not been able to understand why enforcing four space indentation is a problem!
```pan
'/software/components/filecopy/services/{/etc/squid/customized.sh}' = dict(
    'config', format(
        file_contents('features/frontier/customized.sh.file'),
        FRONTIER_LOCAL_NET_STRING,
        FRONTIER_HOST_MONITOR_STRING,
        FRONTIER_CACHE_MEM,
        FRONTIER_CACHE_DIR,
    ),
    'restart', 'service frontier-squid reload',
    'perms', '0644',
);
```
This style is designed to clearly distinguish lists of parameters (for functions and lists) and key-value pairs (for dicts) by indenting each new item with four-spaces. This also has the benefit of allowing changes to any of the items in these lists without polluting diffs with the lines around them. I also personally find this much easier to read, but perhaps I am simply too used to it.

Getting `panlint` to understand continuation lines as things currently stand will be very hard as each line is treated independently , the indent checker however could be made to understand this use case, so perhaps the short term fix for `panlint` is to remove the indentation checks completely.

**Comment by stdweird** [comment]
@jrha i'd prefer current indentation instead of no indentation

also use prefix (and relative prefix) for such examples. there's not need to make such large dml structures for data anymore (but would not solve the indentation in `format()` issue).

**Comment by jouvin** [comment]
@jrha clearly there was a big misunderstanding between us! The style you propose is fine with me... but I messed up quite a few templates because I misunderstood `panlint` requirement... Is there a place where we document the style expected by `panlin`? If not, it would be good to open an issue on the web site to make sure we write it at some point...
