### ISSUE TITLE
How do we get readthedocs master & latest branches updated?

### ISSUE THREAD

**Issue by ned21** [quattor/pan#235]
https://quattor-pan.readthedocs.io/en/master/ was generated from commit 009934a6 which was merged in Nov **2018**. Anyone know how we get this refreshed/who owns the quattor-pan read the docs account?

**Comment by jrha** [comment]
At least myself and @jouvin can maintain it.
I've pushed the build button on readthedocs, let's see what happens.

**Comment by jrha** [comment]
Seems to have built. It looks like it stopped working when GitHub removed integration.
I think I have created an equivalent web-hook to do it automatically again.

**Comment by ned21** [comment]
Thanks, @jrha - my changes all look to have built fine. It looks like they now support a readthedocs.yaml file in the root of the repo so we can store the config alongside code? https://docs.readthedocs.io/en/stable/config-file/index.html

**Comment by jrha** [comment]
Interesting!
