### ISSUE TITLE
root is not a trailing slash

### ISSUE THREAD

**Issue by stdweird** [quattor/pan#237]
the trailing slash is the path
```
something.pan:12: Unnecessary trailing slash at end of profile path
"/" = {
 ^
```

**Comment by jrha** [comment]
Hmm, there is a unit test that checks the following is not flagged:
```pan
'/' = dict();
```
I'll have a play.

**Comment by jrha** [comment]
Odd, doesn't get flagged for me.

```pan
$ cat /tmp/testsdfgsdghsdfh.pan
object template crap;

"/" = {
};
```

```sh
$ /home/jrha/src/jrha/pan/panc/src/main/scripts/panlint/panlint.py --debug /tmp/testsdfgsdghsdfh.pan
DEBUG: 0001 ...          |object template crap;
DEBUG: 0002 Ignored      |
DEBUG: 0003 ...          |"/" = {
DEBUG: ^^^^ String Range |^^^
DEBUG: ^^^^ Path String  |^^^
DEBUG: 0004 ...          |};

0 problems found in total
```

**Comment by stdweird** [comment]
@jrha hmm, we must be running some outdate panlint then. i'll close this

**Comment by ned21** [comment]
I've also seen this recently. We're running the last "released" version (as-in, what comes in the most recent panc release). Maybe we need to release panlint separately?

**Comment by jrha** [comment]
Ah, that's almost certainly the problem, yes we probably do.
