### ISSUE TITLE
multiline not possible using @documentation desc 

### ISSUE THREAD

**Issue by kwaegema** [quattor/pan#84]
```
@documentation{ 
    desc = this is a multiline
           string
}
```

will return an error on compiling:
`Encountered " <KEY> "the "" at line 3, column 13.
Was expecting:
    <EQUALS> ...`

**Comment by loomis** [comment]
If you want a multiline description, then you'll need to use the form:
```
@documentation{
this is a multiline
string as a description
}
```
You cannot use multiline strings when using the key/value format of an annotation.
