### ISSUE TITLE
Add new pan features to the VIM pan plugin

### ISSUE THREAD

**Issue by Pansanel** [quattor/pan#99]
The VIM plugin has not been updated for 4 years. New PAN keywords and syntax should be added.

**Comment by ned21** [comment]
@Pansanel Did you have any time to work on this please? It would be great to have an updated plugin.

**Comment by wpoely86** [comment]
I've added a couple of extra keywords in #213. Is there a list or something with all that has changed in PAN?

**Comment by wpoely86** [comment]
I think I got all of them now in #213
